### ISSUE TITLE
masterPage.js is inside /src (should be in /src/pages)

### ISSUE THREAD

**Issue by l0eix** [shoonia/velo-filesystem#31]
Currently this extension works fine but it places masterPage.js inside of src folder but it should be inside pages folder instead of src.

**Comment by shoonia** [comment]
Hello, @l0eix !

I have checked the code. I see the file has a path in the `pages` folder
https://github.com/shoonia/velo-filesystem/blob/886181da7f34f28b81010b9e9f93ee0a719ccdac/src/module/textModel.ts#L45-L47
but it saves in the `src`
https://github.com/shoonia/velo-filesystem/blob/886181da7f34f28b81010b9e9f93ee0a719ccdac/src/module/downloadFiles.ts#L45

You're right, It should be in the `pages` folder. I'll fix it.

**Comment by shoonia** [comment]
Fixed in new v0.8.0
